
project_id = "qffpioepvkfvpuqdbbnh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[realtime]
enabled = true

[functions.webhooks]
verify_jwt = false
